runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: app/icewinddale/build/index.html
    upload: app/icewinddale/build/index.html

  - url: /(.*)
    static_files: app/icewinddale/build/\1
    upload: app/icewinddale/build/(.*)